# Generated by Django 3.2.7 on 2021-09-16 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_product_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-name',)},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created',)},
        ),
    ]
